### ISSUE TITLE
Tests don't pass on Julia 1.4

### ISSUE THREAD

**Issue by tlienart** [JuliaData/CategoricalArrays.jl#232] opened 2019-12-05 18:25 UTC
```julia
julia> VERSION
v"1.4.0-DEV.527"

julia> Pkg.status("CategoricalArrays")
Status `~/.julia/environments/v1.4/Project.toml`
  [324d7699] CategoricalArrays v0.7.3

(v1.4) pkg> test CategoricalArrays
   Testing CategoricalArrays
 Resolving package versions...
Status `/var/folders/tf/7g89jh3j5tqc9gs97bfxqgc00000gn/T/jl_tKvsuf/Manifest.toml`
(...)
┌ Warning: `eltype(x::CategoricalString)` is deprecated, use `eltype(String(x))` instead.
│   caller = macro expansion at 01_typedef.jl:56 [inlined]
└ @ Core ~/.julia/packages/CategoricalArrays/U3LvJ/test/01_typedef.jl:56
Test Summary: | Pass  Total
01_typedef.jl |   99     99
Test Summary:    | Pass  Total
02_buildorder.jl |    6      6
Test Summary:     | Pass  Total
03_buildfields.jl |    6      6
Test Summary:      | Pass  Total
04_constructors.jl |  121    121
┌ Warning: `eltype(x::CategoricalString)` is deprecated, use `eltype(String(x))` instead.
│   caller = macro expansion at 05_convert.jl:76 [inlined]
└ @ Core ~/.julia/packages/CategoricalArrays/U3LvJ/test/05_convert.jl:76
Test Summary: | Pass  Total
05_convert.jl |  124    124
Test Summary: | Pass  Total
05_copy.jl    |   14     14
show() for CategoricalPool{Date} and its values: Test Failed at /Users/tlienart/.julia/packages/CategoricalArrays/U3LvJ/test/06_show.jl:79
  Expression: sprint(show, pool) == "$(CategoricalPool){$(DateStr),UInt32}([1999-12-01,1991-08-01,1993-10-01])"
   Evaluated: "CategoricalArrays.CategoricalPool{Dates.Date,UInt32}([Dates.Date(1999, 12, 1),Dates.Date(1991, 8, 1),Dates.Date(1993, 10, 1)])" == "CategoricalArrays.CategoricalPool{Dates.Date,UInt32}([1999-12-01,1991-08-01,1993-10-01])"
Stacktrace:
 [1] macro expansion at /Users/tlienart/.julia/packages/CategoricalArrays/U3LvJ/test/06_show.jl:79 [inlined]
 [2] macro expansion at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1110 [inlined]
 [3] top-level scope at /Users/tlienart/.julia/packages/CategoricalArrays/U3LvJ/test/06_show.jl:66
show() for CategoricalPool{Date} and its values: Test Failed at /Users/tlienart/.julia/packages/CategoricalArrays/U3LvJ/test/06_show.jl:80
  Expression: sprint(show, opool) == "$(CategoricalPool){$(DateStr),UInt32}([1991-08-01,1993-10-01,1999-12-01]) with ordered levels"
   Evaluated: "CategoricalArrays.CategoricalPool{Dates.Date,UInt32}([Dates.Date(1991, 8, 1),Dates.Date(1993, 10, 1),Dates.Date(1999, 12, 1)]) with ordered levels" == "CategoricalArrays.CategoricalPool{Dates.Date,UInt32}([1991-08-01,1993-10-01,1999-12-01]) with ordered levels"
Stacktrace:
 [1] macro expansion at /Users/tlienart/.julia/packages/CategoricalArrays/U3LvJ/test/06_show.jl:80 [inlined]
 [2] macro expansion at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1110 [inlined]
 [3] top-level scope at /Users/tlienart/.julia/packages/CategoricalArrays/U3LvJ/test/06_show.jl:66
show() for CategoricalPool{Date} and its values: Test Failed at /Users/tlienart/.julia/packages/CategoricalArrays/U3LvJ/test/06_show.jl:82
  Expression: sprint(show, nv1) == "$(CategoricalValue){$(DateStr),UInt32} 1999-12-01"
   Evaluated: "CategoricalArrays.CategoricalValue{Dates.Date,UInt32} Dates.Date(1999, 12, 1)" == "CategoricalArrays.CategoricalValue{Dates.Date,UInt32} 1999-12-01"
(...)
```

also this was seen on CI:

```
ERROR: LoadError: LoadError: UndefVarError: tostr_sizehint not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:26
 [2] top-level scope at /home/travis/.julia/packages/CategoricalArrays/U3LvJ/src/deprecated.jl:101
 [3] include(::Module, ::String) at ./Base.jl:377
 [4] include(::String) at /home/travis/.julia/packages/CategoricalArrays/U3LvJ/src/CategoricalArrays.jl:1
 [5] top-level scope at /home/travis/.julia/packages/CategoricalArrays/U3LvJ/src/CategoricalArrays.jl:39
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] top-level scope at none:2
 [8] eval at ./boot.jl:331 [inlined]
 [9] eval(::Expr) at ./client.jl:449
 [10] top-level scope at ./none:3
in expression starting at /home/travis/.julia/packages/CategoricalArrays/U3LvJ/src/deprecated.jl:101
in expression starting at /home/travis/.julia/packages/CategoricalArrays/U3LvJ/src/CategoricalArrays.jl:39
ERROR: LoadError: Failed to precompile CategoricalArrays [324d7699-5711-5eae-9e2f-1d82baa6b597] to /home/travis/.julia/compiled/v1.4/CategoricalArrays/RHXoP_28tiW.ji.
```

thoughts?

**Comment by tlienart** [comment] 2019-12-05 19:18
PS: I tried this with `master` as well, same failure.

**Comment by nalimilan** [comment] 2019-12-06 15:03
Duplicate of #230. The printing failure is due to Dates printing having changed on master, but it keeps being reverted before releases so I won't fix it until it's settled.

**Closed by nalimilan** 2019-12-06 15:03 UTC
