### ISSUE TITLE
Nasty interaction with Pluto

### ISSUE THREAD

**Issue by j-fu** [JuliaData/CategoricalArrays.jl#325] opened 2021-02-05 22:17 UTC
Hi there seems to be some nasty interaction with Pluto, see

https://github.com/fonsp/Pluto.jl/issues/895

Things work if downgrading DataFrames to 0.22.3 and CategoricalArrays to 0.9.0

**Comment by bkamins** [comment] 2021-02-05 22:50
Why do you assume it is a problem with CategoricalArrays.jl?

The report says that the problem is CSV.jl and CSV.jl does not depend neither on DataFrames.jl nor on CategoricalArrays.jl now.

What happens if you install just latest CategoricalArrays.jl in an empty environment?

Thank you for reporting this!

**Comment by j-fu** [comment] 2021-02-05 23:13
In my case, the problem occured with DataFrames.jl  without using CSV.jl.

For mwe with DataFrames, see https://gist.github.com/j-fu/ea0f433b2dc439e053bf3bc345e20874
For mwe with CategoricalArrays see https://gist.github.com/j-fu/fc77bd42b5a4e3ce0c421760cdc94787

Of course this problem also could be with pluto (@fonsp ?), but the situation changed with the latest upgrades in CategoricalArrays and DataFrames.

In both cases, the error message is:
```
 ERROR: LoadError: UndefVarError: invrefpool not defined
```

**Comment by bkamins** [comment] 2021-02-05 23:29
`invrefpool` is a problem that you probably do not have latest DataAPI.jl installed. What version of DataAPI.jl do you have?

**Comment by j-fu** [comment] 2021-02-06 00:38
I didn't install it, it comes as a secondary dependency. 
I made sure to have it in the right version, but under Pluto, somehow the older version is drawn in. 
If I really clean up my *global* environment, things start to work. 

I had a look at Pluto, but didn't see what could be  the point.

Anyway, if this dependency is critical, shouldn't you bump the versions in [compat] ? In DataFrames I see 1.4 as requirement, and in  CategoricalArrays I see   DataAPI 1.5.

**Comment by bkamins** [comment] 2021-02-06 08:39
`invrefpool` is not required by current DataFrames.jl release so it cannot be the reason of your problem.
It is required by CategoricalArrays.jl 0.9.2 but it requires DataAPI 1.5 so all should work.

In summary - all is correct in the Project.toml files of the packages, so either:
1. there is a bug in Julia package manager code
2. you did some non standard operation when installing packages

Option 1. is unlikely, but possible, so it would be good to understand what steps got you to have your package repository in an invalid state.

**Comment by j-fu** [comment] 2021-02-06 08:54
Hi, DataFrames has a dependency on PooledArrays which depends DataAPI. I see the requirement for 1.5 there.
So this indeed seems to be ok.

As for  my package installation: nothing special  - just kept adding this and that, and updating regularly. 

So it may boil down to some subtle differences in the workings of Pkg under  REPL and under Pluto. 

After  removing  .julia/packages and .julia/environments, things work. This also means that I lost the "bad state", so I probably won't be able to repeat the problem. However fonsp/Pluto.jl#895 says that I am not the only one... I will suggest my remedy over there...

Anyway, thanks for the quick responses !

**Comment by bkamins** [comment] 2021-02-06 09:01
>  DataFrames has a dependency on PooledArrays

It is true, but DataFrames.jl 0.22.5 release does not enforce PooledArrays.jl 1.1 release, and only PooledArrays.jl 1.1 requires DataAPI.jl 1.5, so assuming you did not do anything fancy (which I understand is the case) the problem is on package manager side.

So, it is most likely that you were hit by package server synchronization issue, which I recently discussed with @StefanKarpinski and @fredrikekre (I am calling them out to show that this problem seems to occur more often than assumed).

**Comment by greimel** [comment] 2021-02-10 21:38
I am encountering the same issue for a few days now, fixed by pinning DataAPI to 1.4.

**Comment by fredrikekre** [comment] 2021-02-11 12:04
> So, it is most likely that you were hit by package server synchronization issue

That would only result in most recently packages beeing missing. The package versions and compat bounds that are there should be consistent.

It seems more likely that https://github.com/fonsp/Pluto.jl/issues/895#issuecomment-775141635 is the problem

**Comment by nalimilan** [comment] 2021-09-17 14:26
Closing as this seems to be fixed in Pluto.

**Closed by nalimilan** 2021-09-17 14:26 UTC
