### ISSUE TITLE
Trouble with `categorical(v)` when `v` is a `SentinelArrays.ChainedVector`

### ISSUE THREAD

**Issue by ablaom** [JuliaData/CategoricalArrays.jl#361] opened 2021-07-27 01:04 UTC
```julia
using SentinelArrays, CategoricalArrays
v = ChainedVector([1:3, 4:5])
@assert v isa AbstractVector{Int}

julia> categorical(v)
ERROR: MethodError: copyto!(::CategoricalArrays.CategoricalVector{Int64, UInt32, Int64, CategoricalArrays.CategoricalValue{Int64, UInt32}, Union{}}, ::ChainedVector{Int64, UnitRange{Int64}}) is ambiguous. Candidates:
  copyto!(dest::Union{SubArray{var"#s5", N, var"#s4", I, L} where {var"#s5", var"#s4"<:(CategoricalArrays.CategoricalArray{T, var"#s3", R, V, C, U} where {var"#s3", V, C, U}), I, L}, CategoricalArrays.CategoricalArray{T, N, R, V, C, U} where {V, C, U}} where {T, N, R<:Integer}, src::AbstractArray) in CategoricalArrays at /Users/anthony/.julia/packages/CategoricalArrays/rDwMt/src/array.jl:615
  copyto!(dest::AbstractVector{T} where T, src::ChainedVector) in SentinelArrays at /Users/anthony/.julia/packages/SentinelArrays/1hMOA/src/chainedvector.jl:326
Possible fix, define
  copyto!(::Union{SubArray{T, 1, var"#s4", I, L} where {T, T1, R<:Integer, var"#s4"<:(CategoricalArrays.CategoricalArray{T1, var"#s3", R, V, C, U} where {var"#s3", V, C, U}), I, L}, CategoricalArrays.CategoricalVector{T, R, V, C, U} where {C, U, T, R<:Integer, V}}, ::ChainedVector)                                                                              
Stacktrace:
 [1] _convert(::Type{CategoricalArrays.CategoricalVector{Int64, UInt32, V, C, U} where {V, C, U}}, A::ChainedVector{Int64, UnitRange{Int64}}; levels::Nothing)
   @ CategoricalArrays ~/.julia/packages/CategoricalArrays/rDwMt/src/array.jl:343
 [2] (CategoricalArrays.CategoricalVector{Int64, UInt32, V, C, U} where {V, C, U})(A::ChainedVector{Int64, UnitRange{Int64}}; levels::Nothing, ordered::Bool)                     
   @ CategoricalArrays ~/.julia/packages/CategoricalArrays/rDwMt/src/array.jl:253
 [3] #categorical#72
   @ ~/.julia/packages/CategoricalArrays/rDwMt/src/array.jl:927 [inlined]
 [4] categorical(A::ChainedVector{Int64, UnitRange{Int64}})
   @ CategoricalArrays ~/.julia/packages/CategoricalArrays/rDwMt/src/array.jl:926
 [5] top-level scope
   @ REPL[83]:1
```

```julia
  [324d7699] CategoricalArrays v0.10.0
  [91c51154] SentinelArrays v1.3.5
```

```julia
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_LTS_PATH = /Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia
  JULIA_PATH = /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia
  JULIA_EGLOT_PATH = /Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia
  JULIA_NUM_THREADS = 5
  JULIA_NIGHTLY_PATH = /Applications/Julia-1.7.app/Contents/Resources/julia/bin/julia
```

**Comment by bkamins** [comment] 2021-07-27 06:02
@quinnj and @nalimilan - this one is a tough issue. We need to decide which package should depend on which.

**Comment by quinnj** [comment] 2021-08-03 05:57
Hmmm, bummer. Yeah, I'd rather not have to have either depend on each other; I wonder if we can play with the method signatures to avoid the ambiguities here.

**Comment by bkamins** [comment] 2021-08-03 07:27
The problem is that on a conceptual level:
* `CategoricalArray` wants to specify how `copyto!` should work when it is a TARGET
* `SentinelArray` wants to specify how `copyto!` should work when it is a SOURCE

So there is no way to avoid ambiguity I feel. If we have to I would rather make CategoricalArrays.jl take SentinelArrays.jl as a dependency. Let us wait to hear what @nalimilan thinks.

**Comment by storopoli** [comment] 2021-08-13 12:04
Yeah I am having issues with:

```julia
transform!(df, [:col1, :col2, :col3, :col4] .=> cateorical; renamecols=false)
```

If I import a `DataFrame` as `CSV.read(..., DataFrame)`. Had to import as `CSV.File(...) |> DataFrame` in order to work.

**Comment by nalimilan** [comment] 2021-08-13 13:40
I'd rather not yet another dependency to CategoricalArrays that isn't strictly needed to use it (we already have JSON, JSON3, StructTypes and RecipesBase). Also, the same issue will affect PooledArrays once we implement the same optimized `copyto!` implementation for sources that implement `DataAPI.refpool` (as we probably should). And any other array type that implements `copyto!` similar to `ChainedVector` will create the same bug.

It looks like this is a problem that should be fixed in Julia. In the past, some functions have been implemented in a way that avoids ambiguity issues. There might be a way to define internal methods so that priority is given to the destination over the source type (or the reverse). Ideally IIRC it's been discussed to allow each package to specify a number giving the priority level of the method, or to say that calling any method defined for `AbstractArray` is fine given that the interface is well defined.

**Comment by bkamins** [comment] 2021-08-13 17:51
> It looks like this is a problem that should be fixed in Julia.

Yes - it should be hopefully fixed in Julia in the long term. However, we need to decide on something before that happens (and in practice it will not happen fast I am afraid). I will ask on Slack in #internal about the opinion what to do. Maybe there will be some reasonable suggestion.

**Comment by bkamins** [comment] 2021-08-14 06:47
Given the discussion on Slack I do not think this is going to be resolved soon.

@nalimilan - would you agree to take SentinelArrays.jl as a dependency then? (I do not like this solution, and I hope it is temporary, but I do not see any other work-around for the time being)

**Comment by nalimilan** [comment] 2021-08-17 09:29
I guess one solution would be to use Requires.jl for this, and also make JSON, JSON3, StructTypes and RecipesBase optional dependencies too.

**Comment by bkamins** [comment] 2021-08-17 14:46
It seems as a best solution for now.

One question regarding Requires.jl - does package loading sequence matter here or not?

**Comment by ablaom** [comment] 2021-08-17 21:31
> I guess one solution would be to use Requires.jl for this, and also make JSON, JSON3, StructTypes and RecipesBase optional dependencies too.

Our experience in MLJModels using using Requires.jl for optional model-code loading was painful and ultimately abandoned. We had issues with latency issues (packages pre-compiling twice) and we suspected it responsible for issues we were never able to resolve before abandoning its use (eg, https://github.com/alan-turing-institute/MLJ.jl/issues/321). I think Requires is a very clever piece of software, but is essentially a hack; and I have heard both its author and Jeff describe it so.

While it's likely the authors of CAs are better familiar with the correct use of Requires.jl than I, my suggestion is that they think two or three times before choosing that route. Personally, I'd rather live with the hard-wired dependencies until Julia comes up with [a better solution](https://github.com/JuliaLang/Pkg.jl/issues/1285) to this kind of thing.

**Comment by timholy** [comment] 2021-08-23 22:03
I can't speak for pre-compiling twice (that sounds bad...), but Requires got a bit less hacky when all "registration" moved into the module `__init__` function. WRT the specific error in from https://github.com/JuliaAI/MLJModels.jl/issues/22,
```julia
using MLJModels.XGBoost_
```
is XGBoost_ loaded conditionally? It may be an order-of-events issue. There might be something fixable about this, but it would probably take some investigation. 

Requires hasn't changed its design much since Julia 1.0 came out, but it has gotten a lot more lightweight than it was back in 2019. I think it contributed ~0.5s to loading time back then, and we've gotten it down to about 1/10th of that. The latest was https://github.com/JuliaPackaging/Requires.jl/pull/101, but https://github.com/JuliaLang/julia/pull/37574 had already gotten it down considerably by that point.

**Comment by bkamins** [comment] 2021-08-23 22:08
@timholy - thank you for commenting on this. Also probably you are the best to answer my earlier question:

> One question regarding Requires.jl - does package loading sequence matter here or not?

Thank you!

@nalimilan - shall we go for Requires.jl then? (and I assume it should go into CategoricalArrays.jl)

**Comment by quinnj** [comment] 2021-08-23 22:16
Yes, perhaps it's worth trying out Requires.jl again; which we could probably use for all those "extra" CategoricalArray dependencies (StructTypes.jl, JSON.jl, etc.).

**Comment by timholy** [comment] 2021-08-23 22:33
> 

It seems like it shouldn't, but... The reason for my thinking it this:
- https://github.com/JuliaPackaging/Requires.jl/blob/7ff79f692d43658c285a80aa10dc29fa29921049/src/Requires.jl#L50-L52 sets up a "package callback"
- https://github.com/JuliaLang/julia/blob/292f1a95e723c1a72011e525e050eaa971ee0085/base/loading.jl#L1022-L1034 runs the package callbacks right after module-loading, which seems like it will trigger...
- ...https://github.com/JuliaPackaging/Requires.jl/blob/7ff79f692d43658c285a80aa10dc29fa29921049/src/require.jl#L95-L104 eagerly

If there are other callbacks, though, perhaps that could mess some stuff up?

**Comment by timholy** [comment] 2021-08-23 22:34
@quinnj just checking if you saw https://julialang.slack.com/archives/C688QKS7Q/p1629552669203500?thread_ts=1629529745.201100&cid=C688QKS7Q

**Comment by timholy** [comment] 2021-08-24 06:29
Upon further reflection, it seems possible that the following may not work (not sure, but be on the lookout for such issues):
```julia
module Inner
# stuff
function __init__()
    @require ...
end
end

module Outer
using Inner
# some top-level expression that expects the `@require` block of `Inner` to have already run
end
```
followed by
```julia
julia> using Outer
```
All would be fine if you typed `using Inner, Outer`, but the problem is that the callbacks may (?) only fire after loading the module specified in the `using` statement. If someone gets a MWE demonstrating this, it would presumably be a simple fix. And again, maybe it is already working, I'm just trying to guess what happened in https://github.com/JuliaAI/MLJModels.jl/issues/22.

**Comment by bkamins** [comment] 2021-08-24 06:32
Thank you for thinking about it. Fortunately with CategoricalArrays.jl and SentinelArrays.jl we shall not have this problem.

**Comment by nalimilan** [comment] 2021-08-24 08:12
OK, so let's try Requires.jl then. If it creates problems it's easy to move to standard dependencies.

**Comment by bkamins** [comment] 2021-09-16 21:03
In https://github.com/JuliaData/DataFrames.jl/issues/2883 the problem was reported again.
@nalimilan - would you be willing to make a fix in CategoricalArrays.jl and make a release?
Thank you!

**Closed** 2021-09-17 16:26 UTC
